import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import NavbarContainer from '@/components/NavbarContainer';
import Navbar from '@/components/Navbar';
import Providers from '@/components/Providers';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin']
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin']
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} grid grid-rows-[auto_1fr] min-h-dvh antialiased`}>
        <Providers>
          <NavbarContainer>
            <Navbar />
          </NavbarContainer>
          {children}
        </Providers>
      </body>
    </html>
  );
}
